name: 'BrowserStack Playwright Inception '
on: [push, pull_request]
jobs:
  ubuntu-job:
    name: 'BrowserStack Playwright Inception Nicholas Onboarding'
    runs-on: ubuntu-latest  # Can be self-hosted runner also
    steps:

    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DEBUG: true
          envkey_BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          envkey_BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          envkey_BROWSERSTACK_DEMO_EMAIL: ${{ secrets.BROWSERSTACK_DEMO_EMAIL }}
          envkey_BROWSERSTACK_DEMO_PASSWORD: ${{ secrets.BROWSERSTACK_DEMO_PASSWORD }}
          file_name: .env

      - name: 'BrowserStack Env Setup'  # Invokes the setup-env action
        uses: browserstack/github-actions/setup-env@master
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      - name: 'BrowserStack Local Tunnel Setup'  # Invokes the setup-local action
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: start
          local-identifier: random

# The next 3 steps are for building the web application to be tested and starting the web server on the runner environment

      - name: 'Checkout the repository'
        uses: actions/checkout@v2

      - name: 'Building web application to be tested'
        working-directory: ./playwright-test
        run: npm install

      # - name: 'Change Root'  # Invokes the actual test script that would run on BrowserStack browsers
      #   run: cd playwright-test   

      - name: 'Running Single test on BrowserStack'
        working-directory: ./playwright-test
        run: npm run test:onboarding   # See sample test script above

      - name: 'BrowserStackLocal Stop'  # Terminating the BrowserStackLocal tunnel connection
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: stop
